### ISSUE TITLE
gpg: keyserver timed out

### ISSUE THREAD

**Issue by tispratik** [phlipper/chef-newrelic-sysmond#6]
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --secret-keyring /tmp/tmp.NwjiQpaT8P --trustdb-name /etc/apt//trustdb.gpg --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyserver subkeys.pgp.net --recv 548C16BF
STDERR: gpg: requesting key 548C16BF from hkp server subkeys.pgp.net
gpg: keyserver timed out
gpg: keyserver receive failed: keyserver error
---- End output of apt-key adv --keyserver subkeys.pgp.net --recv 548C16BF ----
Ran apt-key adv --keyserver subkeys.pgp.net --recv 548C16BF returned 2

This could be related to http://askubuntu.com/questions/134913/cant-add-repo-keys

**Comment by jtescher** [comment]
Same issue. Any way around this?

**Comment by filipegiusti** [comment]
I get this intermittently with puppet. I guess the server can't take the load.

**Comment by tispratik** [comment]
I finally installed newrelic manually using their instruction as i could not get the chef recipe working.

**Comment by jvmccarthy** [comment]
Switched keyserver to `keyserver.ubuntu.com`, which also has the New Relic repository key,

```
override['new_relic']['keyserver'] = 'keyserver.ubuntu.com'
```

**Comment by phlipper** [comment]
Sorry for not responding earlier... As @jvmccarthy pointed out, you can update the value of `node["new_relic"]["keyserver"]`, but I have now provided a more sensible default via #7 so hopefully this won't be necessary anymore.

**Comment by tispratik** [comment]
Thanks everyone!
